---
exclude:
  - '**/vendor/**/*'
linters:
  RequireInputAutocomplete:
    enabled: false
  Rubocop:
    enabled: true
    rubocop_config:
      inherit_from:
        - .rubocop.yml
      Layout/InitialIndentation:
        Enabled: false
      Layout/LineLength:
        Enabled: false
      Layout/TrailingEmptyLines:
        Enabled: false
      Layout/TrailingWhitespace:
        Enabled: false
      Naming/FileName:
        Enabled: false
      Style/FrozenStringLiteralComment:
        Enabled: false
      Lint/UselessAssignment:
        Enabled: false
      Rails/OutputSafety:
        Enabled: false
      Layout/LeadingEmptyLines:
        Enabled: false
      Metrics/BlockLength:
        Enabled: true
      Style/StringConcatenation:
        Enabled: true
      Style/OpenStructUse:
        Enabled: true
