version: "3.9"

services:
  db:
    image: postgres:13.9-alpine
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${POSTGRES_PORT:-5432}:5432

  redis:
    image: redis:7.0.5-alpine
    volumes:
      - redis:/data
    command: redis-server
    ports:
      - ${REDIS_PORT:-6379}:6379
    healthcheck:
      test: redis-cli ping
      interval: 10s
      timeout: 5s
      retries: 5

  sidekiq:
    depends_on:
      - db
      - redis
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/app

  selenium_chrome:
    image: selenium/standalone-chrome:112.0-20230421
    shm_size: 2gb
    logging:
      driver: none
#    volumes:
#      - /dev/shm:/dev/shm
    ports:
      - 5900:5900

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      SELENIUM_REMOTE_URL: ${SELENIUM_REMOTE_URL}
    volumes:
      - .:/app
    ports:
      - ${WEB_PORT:-3001}:3000
    depends_on:
      - db
      - sidekiq
      - selenium_chrome

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - 1025:1025
      - 1080:1080

  adminer:
    image: adminer:4.8.1
    ports:
      - ${ADMINER_PORT:-8080}:8080

volumes:
  db: null
  redis: null